server {
    listen 80;

    server_name tasklytics.app www.tasklytics.app 159.203.26.144;

    location / {
        proxy_pass http://frontend:3000;
    }

    location /api/ {
        proxy_pass http://backend:8000/;
    }
}